[theme]
base = "light"
primaryColor = "#5A7D4D"
backgroundColor = "#FAF7F0"
secondaryBackgroundColor = "#F1ECE1"
textColor = "#222222"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false
