
[theme]
base = "light"
primaryColor = "#5b7a52"
backgroundColor = "#f8f5ef"
secondaryBackgroundColor = "#f1ece1"
textColor = "#262620"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
